import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Urbanist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "600", "800"],
  variable: "--font-urbanist",
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en"  className={urbanist.variable}>
      <body className="bg-gray-100 text-gray-900">
        {children}
      </body>
    </html>
  );
}

